## Ravel    

In [2]:

import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
a_ravel=a.ravel()
print(a_ravel)
print(a.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [8]:
print(id(a))
print(id(a.ravel()))
print(id(a_ravel))

1715329391984
1715330304496
1715329400528


In [13]:
print(f"Data address of 'a':  {a.__array_interface__['data'][0]}")

Data address of 'a':  1715206814208


In [10]:
print(f"Data address of 'a.ravel()':  {a.ravel().__array_interface__['data'][0]}")

Data address of 'a.ravel()':  1715206814208


In [11]:
print(f"Data address of 'a_ravel: ' {a_ravel.__array_interface__['data'][0]}")

Data address of 'a_ravel: ' 1715206814208


In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b = a.flatten()
b

array([1, 2, 3, 4, 5, 6])

In [7]:
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")
print(f"Data address of 'b': {b.__array_interface__['data'][0]}")

Data address of 'a': 2282574019376
Data address of 'b': 2282544535328
