## Creating numpy arrays    

In [ ]:
import numpy as np


[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# list1=[1,2,3,4] 1 dimensional
arr_1=np.array([1,2,3,4])
print(arr_1)
print(type(arr_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [17]:
arr_1

array([1, 2, 3, 4])

In [ ]:
arr_2= np.array([[1,2,3],[4,5,6]])  # 2 dimensional
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [7]:
# Understanding of datatype
arr_3=np.array([1,2,3,4],dtype=np.int8)
print(type(arr_3))

<class 'numpy.ndarray'>


In [9]:
# To know the type of array values
type(arr_3[0])

numpy.int8

## np.arange(start,stop,step)

In [ ]:
print(np.arange(1,11,2))
a= np.array(np.arange(1,11,2))


[1 3 5 7 9]


In [18]:
a

array([1, 3, 5, 7, 9])

In [19]:
print(a)

[1 3 5 7 9]


In [16]:
np.array(a)

array([1, 3, 5, 7, 9])

In [20]:
print(np.array(a))

[1 3 5 7 9]


## np.linspace(start,stop,num=x)

In [24]:
print(np.linspace(1,100,4))

[  1.  34.  67. 100.]


In [33]:
print(np.linspace(1,100,4,dtype=np.int8))

[  1  34  67 100]


In [28]:
a_linspace=np.array(np.linspace(1,10,10))
print(a_linspace)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [32]:
for num in a_linspace:
    print(num)
    print(type(num))

1.0
<class 'numpy.float64'>
2.0
<class 'numpy.float64'>
3.0
<class 'numpy.float64'>
4.0
<class 'numpy.float64'>
5.0
<class 'numpy.float64'>
6.0
<class 'numpy.float64'>
7.0
<class 'numpy.float64'>
8.0
<class 'numpy.float64'>
9.0
<class 'numpy.float64'>
10.0
<class 'numpy.float64'>


## np.zeros(shape)