## 1. A 1D array of numbers from 0 to 9

In [1]:
import numpy as np

In [ ]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


## 2. A 3x3 matrix of all 5s

In [7]:
arr2 = np.full((3, 3), 5)
print(arr2)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


## 3. A 4x4 identity matrix

In [10]:
arr_identity=np.eye(4,4,dtype=int)
print(arr_identity)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
arr_identity_1=np.eye(4)
print(arr_identity_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


## 4. 10 evenly spaced numbers between 1 and 100

In [11]:
arr_linspace=np.linspace(1,100,10)
print(arr_linspace)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## 5. A 2x2 array with random values between 0 and 1

In [12]:
arr_rand=np.random.rand(2,2)
print(arr_rand)

[[0.78798161 0.53885304]
 [0.04652226 0.0463843 ]]
